
export interface CharacterPose {
  name: string;
  anchor: string;
  description: string;
}

export interface CameraShot {
  lens: string;        // e.g. "Wide Angle 24mm"
  angle: string;       // e.g. "Low Angle", "Dutch Angle"
  composition: string; // Description of framing and placement
  focalPoint: string;  // Subject of the shot
}

export interface VFXData {
  lighting: string;       // Strategy: Main source, contrast, rim lighting etc.
  atmosphere: string;     // Environment mood, color palette
  specialEffects: string; // Particles, magic, glows, technical elements
  postProcessing: string; // Keywords: Motion blur, chromatic aberration, etc.
}

export interface StoryBeat {
  id: number;
  title: string;
  narrativeDescription: string; // The physical action summary
  visualSetting: string;        // Location/Scene heading for consistency
  visualDescriptionPlain: string; // Natural English description of the scene
  script: string;               // Combined Dialogue, Monologue, and Narration
  sourceText?: string;          // The exact segment of the original input text
  poses?: CharacterPose[];      // Optional: Generated by Pose Director
  camera?: CameraShot;          // Optional: Generated by Camera Director
  vfx?: VFXData;                // Optional: Generated by VFX Director
  soundDescription?: string;    // Optional: Generated by Sound Director
  generatedImages?: string[];   // Array of Base64 images generated for this beat
  selectedImage?: string;       // The Base64 string of the user-selected "Main" image
}

export interface Character {
  name: string;
  role: string;
  description: string;
  imageRef?: string; // Base64 Data URI
}

export interface Setting {
  name: string;
  description: string;
  imageRef?: string; // Base64 Data URI
}

export interface StoryBible {
  summary: string;
  characters: Character[];
  settings: Setting[];
}

export interface AnalysisResult {
  beats: StoryBeat[];
  bible: StoryBible;
}

export enum AnalysisStatus {
  IDLE = 'IDLE',
  ANALYZING = 'ANALYZING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR'
}

export interface AssetElementState {
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  width: number; // percentage
  height: number; // percentage (or 'auto')
  opacity: number;
}

export interface AssetState {
  generatedTextBoxes: string[];
  generatedSprites: string[];
  activeTextBox: string | null;
  activeSprite: string | null;
  textBoxPrompt: string;
  spritePrompt: string;
  layout: {
    sprite: AssetElementState;
    textbox: AssetElementState;
  };
}